name: Build AMI

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: string
      version:
        description: 'Version of the app'
        required: true
        default: '1.0.0'
        type: string
      deploy:
        description: 'Deploy to production?'
        required: false
        default: 'false'
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy with inputs
        run: |
          echo "Deploying to environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Deploy to production: ${{ github.event.inputs.deploy }}"
